{
 "title": "Postgresql Queries Stats",
 "description": "PostgreSQL Queries Overview Dashboard",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "query_result(pg_up{release=\"$release\"})"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{instance=\"$host\",datname!~\"template.*\"},datname)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Statements Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Statements Calls",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval]) or \nirate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Most Called Queries",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval]) or \nirate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slowest Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Duration of Queries",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_statements_total_time_seconds{datname=~\"$datname\",instance=\"$host\"}[$interval]) or \nirate(pg_stat_statements_total_time_seconds{datname=~\"$datname\",instance=\"$host\"}[5m])) > 0)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Queries Duration",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_total_time_seconds{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Runtime",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_total_time_seconds{datname=~\"$datname\",instance=~\"$host\"}[$interval]) / \n(rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Shared Blocks Dirtied",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_dirtied{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Shared Blocks Catch Hits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_hit{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Shared Blocks  Dirtied",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_dirtied{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Shared Block Cache Hits",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_hit{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Shared Blocks Read",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Shared Blocks Written",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Shared Blocks Read",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Shared Blocks Written",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Blocks I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Local Blocks Dirtied",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_dirtied{datname=~\"$datname\",instance=\"$host\"}[$interval]) * 8)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Local Blocks Cache Hits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_hit{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Local Blocks Dirtied",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_dirtied{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Local Blocks Cache Hits",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_hit{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Local Blocks Read",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Total Local Blocks Written",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Local Blocks Read",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Local Blocks Written",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp Data Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Temp Blocks Read",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_temp_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval]) or \nirate(pg_stat_statements_temp_blks_read{datname=~\"$datname\",instance=\"$host\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Temp Blocks Read",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_temp_blks_read{datname=~\"$datname\",instance=~\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "test1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Temp Blocks Read per Call",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_temp_blks_read{datname=~\"$datname\",instance=~\"$host\"}[$interval]) / \n(rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp Data Written",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temp Blocks Written",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_statements_temp_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temp Blocks Written",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_temp_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp Blocks Written per Call",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 177 },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_temp_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval]) / \n(rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval])>1/6000))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New Slow Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "New Slow Queries for All Databases",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 134 },
     "targets": [
      {
       "expr": "sort_desc(topk(5,sum(irate(pg_stat_statements_total_time_seconds{instance=~\"$host\"}[10m])) by (queryid, datname, user)) unless \ntopk(20,sum(irate(pg_stat_statements_total_time_seconds{instance=~\"$host\"}[10m] offset 7d)) by (queryid, datname, user)))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}